django_auth_example/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from users import views
from users.views import insert
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 别忘记在顶部引入 include 函数
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^$', views.index, name='index'),
    url(r'^insert/$', insert),
    url(r'^users/recommend1/$', views.recommend1),
    url(r'^users/recommend2/$', views.recommend2),
    # url(r'^users/recommend1/users/recommend1/recommend2/$', views.recommend2),
    url(r'^users/showmessage/$', views.showmessage),
]

users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'
urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^showmessage/', views.showmessage, name='showmessage'),

]

users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    nickname = models.CharField(max_length=50, blank=True)

    class Meta(AbstractUser.Meta):
        pass


class Resulttable(models.Model):
    # movieId = models.IntegerField(null=True)  # Field name made lowercase.
    userId = models.IntegerField(null=True)  # Field name made lowercase.
    imdbId = models.IntegerField()  # Field name made lowercase.
    rating = models.DecimalField(max_digits=3, decimal_places=1, blank=True, null=True)

    # title = models.CharField(max_length=50, blank=True, null=True)

    # class Meta:
    #     managed = False
    #     db_table = 'resulttable'

    def __str__(self):
        return str(self.userId) + ':' + str(self.rating)


class Insertposter(models.Model):
    userId = models.IntegerField(null=True)
    title = models.CharField(max_length=200, blank=True, null=False)
    poster = models.CharField(max_length=500, blank=True, null=True)

    def __str__(self):
        return str(self.userId) + ':' + self.poster

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")

users/views.py
import os

from django.shortcuts import redirect

from users.util.ItemBasedCF import *
from users.util.LFM import *
from users.util.UserBasedCF import *
from users.util.database_connect import *
from .forms import RegisterForm
from users.models import Resulttable, Insertposter


# 注册方法
def register(request):
    # 只有当请求为 POST 时，才表示用户提交了注册信息
    if request.method == 'POST':
        form = RegisterForm(request.POST)

        # 验证数据的合法性
        if form.is_valid():  # 如果提交数据合法，调用表单的 save 方法将用户数据保存到数据库
            form.save()

            # 注册成功，跳转回首页
            return redirect('/')
    else:
        pass
        # 请求不是 POST，表明用户正在访问注册页面，展示一个空的注册表单给用户
        form = RegisterForm()

    # 渲染模板
    # 如果用户正在访问注册页面，则渲染的是一个空的注册表单
    # 如果用户通过表单提交注册信息，但是数据验证不合法，则渲染的是一个带有错误信息的表单
    return render(request, '../templates/users/register.html', context={'form': form})


def index(request):
    return render(request, 'users/..//index.html')


def check(request):
    return render((request, 'users/..//index.html'))


# 用于展示用户评过的电影
def showmessage(request):
    usermovieid = []
    usermovietitle = []
    userid = 1003
    # 查询数据库中的数据userID = 1001
    data = Resulttable.objects.filter(userId=userid).values('imdbId')
    for row in data:
        usermovieid.append(row.get('imdbId'))

    try:
        conn = get_conn()
        cur = conn.cursor()
        for i in usermovieid:
            print(i)
            cur.execute('select * from moviegenre3 where imdbId = %s', i)
            rr = cur.fetchall()

            for imdbId, title, poster in rr:
                usermovietitle.append(title)
                print(title)

        # print(poster_result)
    finally:
        conn.close()
    return render(request, 'users/message.html', locals())


def recommend1(request):
    global conn
    USERID = int(request.GET.get("userIdd")) + 1000
    read_mysql_to_csv('users/static/users_resulttable.csv', USERID)  # 追加数据，提高速率
    ratingfile = os.path.join('users/static', 'users_resulttable.csv')

    # usercf = UserBasedCF(ratingfile)
    userid = str(USERID)  # 得到了当前用户的id 1001
    # print(userid)

    # 新的usercf_
    print("start usercf")
    usercf = UserBasedCF(data_file)
    usercf_recom_num = 20
    usercf.load_data(train_size=0.8, normalize=True)
    usercf.users_similarity(normal=False)
    usercf_mae, usercf_rmse = usercf.validate(K=1)
    print("平均绝对误差", usercf_mae, "线性回归的损失函数：", usercf_rmse)
    usercf_pre, usercf_rec = usercf.evaluate(K=1)
    print("准确率:", usercf_pre, "召回率：", usercf_rec)
    result_list = usercf.predict(USERID)
    for i in result_list[:usercf_recom_num]:
        matrix.append(i[0])
    # print(matrix)

    # 使用lfm算法
    print("开始lfm算法")
    lfm = LFM(train_size=0.8, ratio=1)
    if (os.path.exists(model_path)):
        lfm.load()
    else:
        lfm.train()
        print("LFM训练结束")
        mae, rmse = lfm.validate()
        print('平均绝对误差:', mae, '线性回归的损失函数：', rmse)  # rmse:均方根误差 mae:平均绝对误差
    pre, rec, matrix2 = lfm.evaluate(USERID)
    print('准确率:', pre*10, '召回率:', rec)
    # Precision 就是检索出来的条目中（比如：文档、网页等）有多少是准确的，Recall就是所有准确的条目有多少被检索出来了。

    matrix1 = matrix + matrix2

    try:
        conn = get_conn()
        cur = conn.cursor()
        Insertposter.objects.filter(userId=USERID).delete()  # 清空insertposter库，防止以前的数据产生影响
        for i in matrix1:  # 遍历推荐结果矩阵
            cur.execute('select * from moviegenre3 where imdbId = %s', i)
            rr = cur.fetchall()
            for imdbId, title, poster in rr:
                if (Insertposter.objects.filter(title=title)):
                    continue
                else:
                    Insertposter.objects.create(userId=USERID, title=title, poster=poster)

        # print(poster_result)
    finally:
        conn.close()
    results = Insertposter.objects.filter(userId=USERID)
    return render(request, 'users/movieRecommend.html', locals())
    # return render(request, 'users/..//index.html', locals())

def recommend2(request):
    global conn
    USERID = 1003

    userid = str(USERID)  # 得到了当前用户的id 1001


    # 使用lfm算法
    print("开始lfm算法")
    lfm = LFM(train_size=0.8, ratio=1)
    if (os.path.exists(model_path)):
        lfm.load()
    else:
        lfm.train()
        print("LFM训练结束")
        mae, rmse = lfm.validate()
        print('平均绝对误差:', mae, '线性回归的损失函数：', rmse)  # rmse:均方根误差 mae:平均绝对误差
    pre, rec, matrix2 = lfm.evaluate(USERID)
    print('准确率:', pre*10, '召回率:', rec)
    # Precision 就是检索出来的条目中（比如：文档、网页等）有多少是准确的，Recall就是所有准确的条目有多少被检索出来了。
    try:
        conn = get_conn()
        cur = conn.cursor()
        Insertposter.objects.filter(userId=USERID).delete()  # 清空insertposter库，防止以前的数据产生影响
        for i in matrix2:  # 遍历推荐结果矩阵
            cur.execute('select * from moviegenre3 where imdbId = %s', i)
            rr = cur.fetchall()
            for imdbId, title, poster in rr:
                if (Insertposter.objects.filter(title=title)):
                    continue
                else:
                    Insertposter.objects.create(userId=USERID, title=title, poster=poster)

        # print(poster_result)
    finally:
        conn.close()
    results = Insertposter.objects.filter(userId=USERID)
    return render(request, 'users/movieRecommend.html', locals())




# 用于展示推荐数据，调用计算函数


# def recommend2(request):
#     print("recommend2被运行")
#     USERID = int(request.GET.get('userIdd')) + 1000
#     # USERID = 1001
#     # Insertposter.objects.filter(userId=USERID).delete()
#     # selectMysql()
#     read_mysql_to_csv2('users/static/users_resulttable2.csv', USERID)  # 追加数据，提高速率
#     ratingfile2 = os.path.join('users/static', 'users_resulttable2.csv')
#     itemcf = ItemBasedCF()
#     # userid = '1001'
#     userid = str(USERID)  # 得到了当前用户的id
#     itemcf.generate_dataset(ratingfile2)
#     itemcf.calc_movie_sim()
#     itemcf.recommend(userid)  # 得到imdbId号
#
#     # 先删除所有数据
#
#     try:
#         conn = get_conn()
#         cur = conn.cursor()
#         # Insertposter.objects.filter(userId=USERID).delete()
#         for i in matrix2:
#             cur.execute('select * from moviegenre3 where imdbId = %s', i)
#             rr = cur.fetchall()
#             for imdbId, title, poster in rr:
#                 # print(value)         #value才是真正的海报链接
#                 if (Insertposter.objects.filter(title=title)):
#                     continue
#                 else:
#                     Insertposter.objects.create(userId=USERID, title=title, poster=poster)
#
#         # print(poster_result)
#     finally:
#         conn.close()
#         results = Insertposter.objects.filter(userId=USERID)  # 从这里传递给html= Insertposter.objects.all()
#
#     return render(request, 'users/movieRecommend2.html', locals())
#     # return HttpResponseRedirect('movieRecommend.html', locals())


#
# if __name__ == '__main__':
#     ratingfile2 = os.path.join('static', 'users_resulttable.csv')  # 一共671个用户
#
#     usercf = UserBasedCF()
#     userId = '1'
#     # usercf.initial_dataset(ratingfile1)
#     usercf.generate_dataset(ratingfile2)
#     usercf.calc_user_sim()
#     # usercf.evaluate()
#     usercf.recommend(userId)
#     # 给用户推荐10部电影  输出的是‘movieId’,兴趣度

templates/users/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户评过的电影</title>

    <style>
        h2{
            text-align: center;
            font-family: Georgia, serif;
            font-weight: bold
        }
        li{
            list-style: none;
            text-align: center;
            {#display: inline-block;#}
        }
    </style>
</head>


<h2>您评价过下列电影：</h2>
<br/>
{% for dd in usermovietitle %}
    <li>
    <p>{{ dd }}</p>
    </li>

{%  endfor %}


<a href="{% url 'index' %}"><button style="height: 25px;align-content: center;margin-left: 650px" >返回主页</button></a>

</body>
</html>

templates/users/movieRecommend.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>推荐电影页面</title>

    <style>
        img{
            width: 182px;
            height: 268px;
            margin: 20px 30px;
        }
        li{
            list-style: none;
            display: inline-block;
        }
        div.main{
            margin: 0px 150px;
            border: 100px;
        }
        #recommend2{
                position:absolute;
                left:700px;
                background-color: #008CBA;
                color: white;
                padding: 5px 12px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 4px 2px;
                cursor: pointer;
            }

    </style>
</head>
<body>
<h1 style="text-align: center">和您有相似兴趣的用户也喜欢下列电影：</h1>
<div class="main">

    {% for result in results %}
    <li>
        <p style="font-size:10px;width:200px;text-align: center">{{ result.title }}</p>
        <img src="{{ result.poster }}" onerror='this.src="/static/img/a1.jpg"'>
    </li>

{%  endfor %}


</div>

    <a href="{% url 'index' %}"><button style="height: 25px;align-content: center;margin-left: 650px" >返回主页</button></a>

</body>
</html>

templates/users/movieRecommend2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>推荐电影页面</title>

        <style>

        li{
            list-style: none;
            display: inline-block;
        }
    </style>
</head>
<body>
<h1>和您喜欢的电影相似的有下列电影：</h1>
{% for result in results %}
    <li>
        <p>{{ result.title }}</p>
        <img src="{{ result.poster }}" alt="">
    </li>

{%  endfor %}
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<title>注册</title>
	<link rel="stylesheet" href="/static/assets/libs/particles/css/style.css">
	<link rel="stylesheet" href="/static/assets/libs/sweetalert2/sweetalert2.min.css">
	<link rel="stylesheet" href="/static/assets/css/base.css">
	<link rel="stylesheet" href="/static/assets/css/login.css">
	<style>
	.errorlist {
            color: red;
        }
    form{
    }

	</style>
</head>
<body>
	<!-- particles.js container -->
	<div id="particles-js"></div>
	<div id="wrapper">
		<div>
			<img src="/static/assets/img/zhihu_logo.png" />
		</div>
		<nav class="switch_nav">
			<a href="javascript:;" id="switch_signup" class="switch_btn on">注册</a>
			<a href="{% url 'login' %}" id="switch_login" class="switch_btn">登陆</a>
			<div class="switch_bottom" id="switch_bottom"></div>
		</nav>
		<form method="post" action="{% url 'users:register' %}" style="background: rgb(247,250,252);">
			{% csrf_token %}
			{% for field in form %}
			<ul class="group_input">
				
				<li>
					{{ field.label_tag }}<p>{{ field }}
				</li>
				<div id="footer">
					<span>
					{{ field.errors }}
{#                    {% if field.help_text %}#}
{#                        <b class="help text-small text-muted">{{ field.help_text|safe }}</b>#}
{#                    {% endif %}#}
					</span>
				</div>
			</ul>
                    {% endfor %}
			<button type="submit" class="submit_btn" id="btnSubmit" onclick="sendSubmit()"style="float: bottom">注册个性化推荐系统</button>
		
		</form>
		
		
		
		
		
	</div>
	<script src="/static/assets/libs/jquery-1.12.4/jquery.min.js"></script>
	<script src="/static/assets/libs/sweetalert2/sweetalert2.min.js"></script>
	<script src="/static/assets/libs/particles/particles.min.js"></script>
	<script src="/static/assets/libs/particles/js/app.js"></script>
	<!-- <script src="../assets/libs/particles/js/lib/stats.js"></script>

	-->
	<script>
		var count_particles, stats, update;
		stats = new Stats;
		stats.setMode(0);
		stats.domElement.style.position = 'absolute';
		stats.domElement.style.left = '0px';
		stats.domElement.style.top = '0px';
		document.body.appendChild(stats.domElement);
		count_particles = document.querySelector('.js-count-particles');
		update = function() {
			stats.begin();
			stats.end();
			if (window.pJSDom[0].pJS.particles && window.pJSDom[0].pJS.particles.array) {
				count_particles.innerText = window.pJSDom[0].pJS.particles.array.length;
			}
			requestAnimationFrame(update);
		};
		requestAnimationFrame(update);
	</script>	
	
	
</body>
</html>